// Geofabrik country/region list for .poly boundary downloads.
// Each entry: { name: display name, url: Geofabrik path (without .poly extension) }
// Full URL: https://download.geofabrik.de/{url}.poly

const GEOFABRIK_COUNTRIES = [
  // --- Europe ---
  { name: "Albania", url: "europe/albania" },
  { name: "Andorra", url: "europe/andorra" },
  { name: "Austria", url: "europe/austria" },
  { name: "Belarus", url: "europe/belarus" },
  { name: "Belgium", url: "europe/belgium" },
  { name: "Bosnia and Herzegovina", url: "europe/bosnia-herzegovina" },
  { name: "Bulgaria", url: "europe/bulgaria" },
  { name: "Croatia", url: "europe/croatia" },
  { name: "Cyprus", url: "europe/cyprus" },
  { name: "Czech Republic", url: "europe/czech-republic" },
  { name: "Denmark", url: "europe/denmark" },
  { name: "Estonia", url: "europe/estonia" },
  { name: "Faroe Islands", url: "europe/faroe-islands" },
  { name: "Finland", url: "europe/finland" },
  { name: "France", url: "europe/france" },
  { name: "Georgia", url: "europe/georgia" },
  { name: "Germany", url: "europe/germany" },
  { name: "Great Britain", url: "europe/great-britain" },
  { name: "Greece", url: "europe/greece" },
  { name: "Hungary", url: "europe/hungary" },
  { name: "Iceland", url: "europe/iceland" },
  { name: "Ireland and Northern Ireland", url: "europe/ireland-and-northern-ireland" },
  { name: "Isle of Man", url: "europe/isle-of-man" },
  { name: "Italy", url: "europe/italy" },
  { name: "Kosovo", url: "europe/kosovo" },
  { name: "Latvia", url: "europe/latvia" },
  { name: "Liechtenstein", url: "europe/liechtenstein" },
  { name: "Lithuania", url: "europe/lithuania" },
  { name: "Luxembourg", url: "europe/luxembourg" },
  { name: "Macedonia (North)", url: "europe/macedonia" },
  { name: "Malta", url: "europe/malta" },
  { name: "Moldova", url: "europe/moldova" },
  { name: "Monaco", url: "europe/monaco" },
  { name: "Montenegro", url: "europe/montenegro" },
  { name: "Netherlands", url: "europe/netherlands" },
  { name: "Norway", url: "europe/norway" },
  { name: "Poland", url: "europe/poland" },
  { name: "Portugal", url: "europe/portugal" },
  { name: "Romania", url: "europe/romania" },
  { name: "Serbia", url: "europe/serbia" },
  { name: "Slovakia", url: "europe/slovakia" },
  { name: "Slovenia", url: "europe/slovenia" },
  { name: "Spain", url: "europe/spain" },
  { name: "Sweden", url: "europe/sweden" },
  { name: "Switzerland", url: "europe/switzerland" },
  { name: "Turkey", url: "europe/turkey" },
  { name: "Ukraine", url: "europe/ukraine" },

  // --- North America ---
  { name: "Canada", url: "north-america/canada" },
  { name: "Mexico", url: "north-america/mexico" },
  { name: "USA", url: "north-america/us" },
  // US states
  { name: "USA - Alabama", url: "north-america/us/alabama" },
  { name: "USA - Alaska", url: "north-america/us/alaska" },
  { name: "USA - Arizona", url: "north-america/us/arizona" },
  { name: "USA - Arkansas", url: "north-america/us/arkansas" },
  { name: "USA - California", url: "north-america/us/california" },
  { name: "USA - Colorado", url: "north-america/us/colorado" },
  { name: "USA - Connecticut", url: "north-america/us/connecticut" },
  { name: "USA - Delaware", url: "north-america/us/delaware" },
  { name: "USA - District of Columbia", url: "north-america/us/district-of-columbia" },
  { name: "USA - Florida", url: "north-america/us/florida" },
  { name: "USA - Georgia", url: "north-america/us/georgia" },
  { name: "USA - Hawaii", url: "north-america/us/hawaii" },
  { name: "USA - Idaho", url: "north-america/us/idaho" },
  { name: "USA - Illinois", url: "north-america/us/illinois" },
  { name: "USA - Indiana", url: "north-america/us/indiana" },
  { name: "USA - Iowa", url: "north-america/us/iowa" },
  { name: "USA - Kansas", url: "north-america/us/kansas" },
  { name: "USA - Kentucky", url: "north-america/us/kentucky" },
  { name: "USA - Louisiana", url: "north-america/us/louisiana" },
  { name: "USA - Maine", url: "north-america/us/maine" },
  { name: "USA - Maryland", url: "north-america/us/maryland" },
  { name: "USA - Massachusetts", url: "north-america/us/massachusetts" },
  { name: "USA - Michigan", url: "north-america/us/michigan" },
  { name: "USA - Minnesota", url: "north-america/us/minnesota" },
  { name: "USA - Mississippi", url: "north-america/us/mississippi" },
  { name: "USA - Missouri", url: "north-america/us/missouri" },
  { name: "USA - Montana", url: "north-america/us/montana" },
  { name: "USA - Nebraska", url: "north-america/us/nebraska" },
  { name: "USA - Nevada", url: "north-america/us/nevada" },
  { name: "USA - New Hampshire", url: "north-america/us/new-hampshire" },
  { name: "USA - New Jersey", url: "north-america/us/new-jersey" },
  { name: "USA - New Mexico", url: "north-america/us/new-mexico" },
  { name: "USA - New York", url: "north-america/us/new-york" },
  { name: "USA - North Carolina", url: "north-america/us/north-carolina" },
  { name: "USA - North Dakota", url: "north-america/us/north-dakota" },
  { name: "USA - Ohio", url: "north-america/us/ohio" },
  { name: "USA - Oklahoma", url: "north-america/us/oklahoma" },
  { name: "USA - Oregon", url: "north-america/us/oregon" },
  { name: "USA - Pennsylvania", url: "north-america/us/pennsylvania" },
  { name: "USA - Rhode Island", url: "north-america/us/rhode-island" },
  { name: "USA - South Carolina", url: "north-america/us/south-carolina" },
  { name: "USA - South Dakota", url: "north-america/us/south-dakota" },
  { name: "USA - Tennessee", url: "north-america/us/tennessee" },
  { name: "USA - Texas", url: "north-america/us/texas" },
  { name: "USA - Utah", url: "north-america/us/utah" },
  { name: "USA - Vermont", url: "north-america/us/vermont" },
  { name: "USA - Virginia", url: "north-america/us/virginia" },
  { name: "USA - Washington", url: "north-america/us/washington" },
  { name: "USA - West Virginia", url: "north-america/us/west-virginia" },
  { name: "USA - Wisconsin", url: "north-america/us/wisconsin" },
  { name: "USA - Wyoming", url: "north-america/us/wyoming" },

  // --- South America ---
  { name: "Argentina", url: "south-america/argentina" },
  { name: "Bolivia", url: "south-america/bolivia" },
  { name: "Brazil", url: "south-america/brazil" },
  { name: "Chile", url: "south-america/chile" },
  { name: "Colombia", url: "south-america/colombia" },
  { name: "Ecuador", url: "south-america/ecuador" },
  { name: "Paraguay", url: "south-america/paraguay" },
  { name: "Peru", url: "south-america/peru" },
  { name: "Suriname", url: "south-america/suriname" },
  { name: "Uruguay", url: "south-america/uruguay" },
  { name: "Venezuela", url: "south-america/venezuela" },

  // --- Asia ---
  { name: "Afghanistan", url: "asia/afghanistan" },
  { name: "Bangladesh", url: "asia/bangladesh" },
  { name: "China", url: "asia/china" },
  { name: "India", url: "asia/india" },
  { name: "Indonesia", url: "asia/indonesia" },
  { name: "Iran", url: "asia/iran" },
  { name: "Iraq", url: "asia/iraq" },
  { name: "Israel and Palestine", url: "asia/israel-and-palestine" },
  { name: "Japan", url: "asia/japan" },
  { name: "Jordan", url: "asia/jordan" },
  { name: "Kazakhstan", url: "asia/kazakhstan" },
  { name: "Malaysia and Singapore", url: "asia/malaysia-singapore-brunei" },
  { name: "Mongolia", url: "asia/mongolia" },
  { name: "Nepal", url: "asia/nepal" },
  { name: "Pakistan", url: "asia/pakistan" },
  { name: "Philippines", url: "asia/philippines" },
  { name: "South Korea", url: "asia/south-korea" },
  { name: "Sri Lanka", url: "asia/sri-lanka" },
  { name: "Taiwan", url: "asia/taiwan" },
  { name: "Thailand", url: "asia/thailand" },
  { name: "Vietnam", url: "asia/vietnam" },

  // --- Africa ---
  { name: "Algeria", url: "africa/algeria" },
  { name: "Egypt", url: "africa/egypt" },
  { name: "Ethiopia", url: "africa/ethiopia" },
  { name: "Kenya", url: "africa/kenya" },
  { name: "Morocco", url: "africa/morocco" },
  { name: "Nigeria", url: "africa/nigeria" },
  { name: "South Africa", url: "africa/south-africa" },
  { name: "Tanzania", url: "africa/tanzania" },

  // --- Oceania ---
  { name: "Australia", url: "australia-oceania/australia" },
  { name: "New Zealand", url: "australia-oceania/new-zealand" },

  // --- Regions / Subcontinents ---
  { name: "Europe (entire)", url: "europe" },
  { name: "North America (entire)", url: "north-america" },
  { name: "South America (entire)", url: "south-america" },
  { name: "Asia (entire)", url: "asia" },
  { name: "Africa (entire)", url: "africa" },
  { name: "Australia and Oceania (entire)", url: "australia-oceania" },
  { name: "Central America", url: "central-america" },
];
